name: Update Branch with Upstream Changes

on:
  push:
    branches:
      - master  # 当你向 master 分支推送时触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有历史记录

      - name: Set up Git
        run: |
          git config user.name "ZT229"  # 替换为你的 GitHub 用户名
          git config user.email "2432702069@qq.com"  # 替换为你的邮箱

      - name: Add Upstream Remote
        run: |
          if ! git remote get-url upstream; then
            git remote add upstream https://github.com/kenzok8/small.git  # 替换为原始仓库的 URL
          fi

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes into Your Branch
        run: |
          git checkout self  # 替换为你的新分支名称
          git merge upstream/master || {
            echo "合并过程中出现冲突，请手动解决。"
            exit 1
          }

      - name: Push Changes
        run: |
          git push origin self  # 推送到你的新分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 进行身份验证
